### ISSUE TITLE
how can i put this in a webpage ?

### ISSUE THREAD

**Issue by nikhildeshmukh** [tmconsulting/amadeus-console-emulator#3]
I need to put this on a webpage, How can i do that

**Comment by smgladkovskiy** [comment]
Hi, @nikhildeshmukh!

This was build not for webpage. It is used as console.

Try to use some kind of websockets to emulate [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) actions
